GAME = {
  MAX_PLAYERS = 4,
  MIN_PLAYERS = 2,
  OUTER_GRID_COL_COUNT = 17,
  OUTER_GRID_ROW_COUNT = 9,
  INNER_GRID_COL_COUNT = 13,
  INNER_GRID_ROW_COUNT = 7,
  SPAWN_TILE_COUNT = 12,
  GAME_WIDTH = 272,
  GAME_HEIGHT = 144,
  PROJECTILE_TYPES = {
    NONE = 0,
    ARROW = 1,
    BULLET = 2,
    MAGIC = 3,
  },
}

PLAYER = {
  ACTIONS = {
    NONE = 0,
    BASIC = 1,
  },
}
MIN_Z_INDEX = -4999
MAX_Z_INDEX = 5000

UPGRADE_KEYS = {
  BOMBS = "available_bombs",
  BOMB_RADIUS = "bomb_radius",
  SPEED = "speed",
}
